//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.239
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter.DB.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Converter.DB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE DATABASE [дмж] ON  PRIMARY 
        ///( NAME = N&apos;пустаясистема&apos;, FILENAME = N&apos;Z:\дмжv2\дмжv2.mdf&apos; , SIZE = 41467456KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
        /// FILEGROUP [ASSEMBLY] 
        ///( NAME = N&apos;Assembly&apos;, FILENAME = N&apos;Z:\дмжv2\Assembly.ndf&apos; , SIZE = 32768KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
        /// FILEGROUP [BOOL_DATA] 
        ///( NAME = N&apos;Bool Rows&apos;, FILENAME = N&apos;Z:\дмжv2\Bool Rows.ndf&apos; , SIZE = 930624KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5%), 
        /// FILEGROUP [BOOL_INDEX] 
        ///( NAME = N&apos;Bool Index&apos;, FILENAME = N&apos;Z: [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string create_sql {
            get {
                return ResourceManager.GetString("create_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /*
        ///Run this script on:
        ///
        ///        10.1.1.201.111    -  This database will be modified
        ///
        ///to synchronize it with:
        ///
        ///        10.1.1.201.артлайф5
        ///
        ///You are recommended to back up your database before running this script
        ///
        ///Script created by SQL Compare version 8.2.0 from Red Gate Software Ltd at 30.01.2012 3:13:45
        ///
        ///*/
        ///SET NUMERIC_ROUNDABORT OFF
        ///GO
        ///SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
        ///GO
        ///IF EXISTS (SELECT * FROM tempdb..sysobjects WHERE [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string sql {
            get {
                return ResourceManager.GetString("sql", resourceCulture);
            }
        }
    }
}
