//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1008
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosService.Files {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Files.IFile")]
    public interface IFile {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (DownloadRequest) сообщения DownloadRequest не соответствует значению по умолчанию (ПолучитьФайл).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFile/ПолучитьФайл", ReplyAction="http://tempuri.org/IFile/ПолучитьФайлResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RosService.Files.DownloadResponce ПолучитьФайл(RosService.Files.DownloadRequest request);
        
        // CODEGEN: Параметр "ПолучитьФайлПолностьюResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFile/ПолучитьФайлПолностью", ReplyAction="http://tempuri.org/IFile/ПолучитьФайлПолностьюResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RosService.Files.ПолучитьФайлПолностьюResponse ПолучитьФайлПолностью(RosService.Files.ПолучитьФайлПолностьюRequest request);
        
        // CODEGEN: Параметр "ПолучитьФайлПолностьюПоНазваниюResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFile/ПолучитьФайлПолностьюПоНазванию", ReplyAction="http://tempuri.org/IFile/ПолучитьФайлПолностьюПоНазваниюResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RosService.Files.ПолучитьФайлПолностьюПоНазваниюResponse ПолучитьФайлПолностьюПоНазванию(RosService.Files.ПолучитьФайлПолностьюПоНазваниюRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (UploadRequest) сообщения UploadRequest не соответствует значению по умолчанию (СохранитьФайл).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFile/СохранитьФайл", ReplyAction="http://tempuri.org/IFile/СохранитьФайлResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RosService.Files.UploadResponce СохранитьФайл(RosService.Files.UploadRequest request);
        
        // CODEGEN: Параметр "id_node" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFile/СохранитьФайлПолностью", ReplyAction="http://tempuri.org/IFile/СохранитьФайлПолностьюResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RosService.Files.СохранитьФайлПолностьюResponse СохранитьФайлПолностью(RosService.Files.СохранитьФайлПолностьюRequest request);
        
        // CODEGEN: Параметр "id_node" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFile/СохранитьФайлПолностьюАсинхронно")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void СохранитьФайлПолностьюАсинхронно(RosService.Files.СохранитьФайлПолностьюАсинхронно request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ОтчетRequest) сообщения ОтчетRequest не соответствует значению по умолчанию (Отчет).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFile/Отчет", ReplyAction="http://tempuri.org/IFile/ОтчетResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RosService.Files.ОтчетResponce Отчет(RosService.Files.ОтчетRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ОтчетКонструкторRequest) сообщения ОтчетКонструкторRequest не соответствует значению по умолчанию (ОтчетКонструктор).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFile/ОтчетКонструктор", ReplyAction="http://tempuri.org/IFile/ОтчетКонструкторResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RosService.Files.ОтчетResponce ОтчетКонструктор(RosService.Files.ОтчетКонструкторRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ОтчетДанныеRequest) сообщения ОтчетДанныеRequest не соответствует значению по умолчанию (ОтчетДанные).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFile/ОтчетДанные", ReplyAction="http://tempuri.org/IFile/ОтчетДанныеResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RosService.Files.DownloadResponce ОтчетДанные(RosService.Files.ОтчетДанныеRequest request);
        
        // CODEGEN: Параметр "ПолучитьФайлПросмотрResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFile/ПолучитьФайлПросмотр", ReplyAction="http://tempuri.org/IFile/ПолучитьФайлПросмотрResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RosService.Files.ПолучитьФайлПросмотрResponse ПолучитьФайлПросмотр(RosService.Files.ПолучитьФайлПросмотрRequest request);
        
        // CODEGEN: Параметр "ПолучитьФайлПросмотрПоНазваниюResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFile/ПолучитьФайлПросмотрПоНазванию", ReplyAction="http://tempuri.org/IFile/ПолучитьФайлПросмотрПоНазваниюResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RosService.Files.ПолучитьФайлПросмотрПоНазваниюResponse ПолучитьФайлПросмотрПоНазванию(RosService.Files.ПолучитьФайлПросмотрПоНазваниюRequest request);
        
        // CODEGEN: Параметр "GetMimeTypeResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFile/GetMimeType", ReplyAction="http://tempuri.org/IFile/GetMimeTypeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RosService.Files.GetMimeTypeResponse GetMimeType(RosService.Files.GetMimeTypeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Data")]
    public enum Хранилище {
        
        /// <remarks/>
        Оперативное,
        
        /// <remarks/>
        Конфигурация,
        
        /// <remarks/>
        Корзина,
        
        /// <remarks/>
        Статистика,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string user;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RosService.Files.Хранилище хранилище;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal id_file;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(string domain, string user, RosService.Files.Хранилище хранилище, decimal id_file) {
            this.domain = domain;
            this.user = user;
            this.хранилище = хранилище;
            this.id_file = id_file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadResponce", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadResponce {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public DownloadResponce() {
        }
        
        public DownloadResponce(string FileName, long Length, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.FileByteStream = FileByteStream;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Files")]
    public partial class СлойИзображения : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HorizontalAlign horizontalAlignField;
        
        private VerticalAlign verticalAlignField;
        
        private double heightField;
        
        private object id_fileField;
        
        private double widthField;
        
        private int xField;
        
        private int yField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HorizontalAlign HorizontalAlign {
            get {
                return this.horizontalAlignField;
            }
            set {
                this.horizontalAlignField = value;
                this.RaisePropertyChanged("HorizontalAlign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VerticalAlign VerticalAlign {
            get {
                return this.verticalAlignField;
            }
            set {
                this.verticalAlignField = value;
                this.RaisePropertyChanged("VerticalAlign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public object id_file {
            get {
                return this.id_fileField;
            }
            set {
                this.id_fileField = value;
                this.RaisePropertyChanged("id_file");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Files")]
    public enum HorizontalAlign {
        
        /// <remarks/>
        Left,
        
        /// <remarks/>
        Right,
        
        /// <remarks/>
        Center,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Files")]
    public enum VerticalAlign {
        
        /// <remarks/>
        Top,
        
        /// <remarks/>
        Bottom,
        
        /// <remarks/>
        Center,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Files")]
    public partial class КонструкторИзображения : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool обрезатьПустоеМестоField;
        
        private bool прозрачныйФонField;
        
        private СлойИзображения[] слоиField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ОбрезатьПустоеМесто {
            get {
                return this.обрезатьПустоеМестоField;
            }
            set {
                this.обрезатьПустоеМестоField = value;
                this.RaisePropertyChanged("ОбрезатьПустоеМесто");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool ПрозрачныйФон {
            get {
                return this.прозрачныйФонField;
            }
            set {
                this.прозрачныйФонField = value;
                this.RaisePropertyChanged("ПрозрачныйФон");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        public СлойИзображения[] Слои {
            get {
                return this.слоиField;
            }
            set {
                this.слоиField = value;
                this.RaisePropertyChanged("Слои");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ШаблонОтчета.Колонка", Namespace="http://schemas.datacontract.org/2004/07/RosService.Files")]
    public partial class ШаблонОтчетаКолонка : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string атрибутField;
        
        private string названиеField;
        
        private double размерField;
        
        private ШаблонОтчетаТипЗначения типЗначенияField;
        
        private string форматField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Атрибут {
            get {
                return this.атрибутField;
            }
            set {
                this.атрибутField = value;
                this.RaisePropertyChanged("Атрибут");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Название {
            get {
                return this.названиеField;
            }
            set {
                this.названиеField = value;
                this.RaisePropertyChanged("Название");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Размер {
            get {
                return this.размерField;
            }
            set {
                this.размерField = value;
                this.RaisePropertyChanged("Размер");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ШаблонОтчетаТипЗначения ТипЗначения {
            get {
                return this.типЗначенияField;
            }
            set {
                this.типЗначенияField = value;
                this.RaisePropertyChanged("ТипЗначения");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Формат {
            get {
                return this.форматField;
            }
            set {
                this.форматField = value;
                this.RaisePropertyChanged("Формат");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ШаблонОтчета.ТипЗначения", Namespace="http://schemas.datacontract.org/2004/07/RosService.Files")]
    public enum ШаблонОтчетаТипЗначения {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Number,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Files")]
    public partial class ШаблонОтчета : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool верхнийКолонтитулField;
        
        private string[] группировкиField;
        
        private string[] запросыField;
        
        private ШаблонОтчетаКолонка[] колонкиField;
        
        private string названиеОтчетаField;
        
        private bool нижнийКолонтитулField;
        
        private ШаблонОтчетаОриентация ориентацияСтраницыField;
        
        private ФорматОтчета форматОтчетаField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ВерхнийКолонтитул {
            get {
                return this.верхнийКолонтитулField;
            }
            set {
                this.верхнийКолонтитулField = value;
                this.RaisePropertyChanged("ВерхнийКолонтитул");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] Группировки {
            get {
                return this.группировкиField;
            }
            set {
                this.группировкиField = value;
                this.RaisePropertyChanged("Группировки");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] Запросы {
            get {
                return this.запросыField;
            }
            set {
                this.запросыField = value;
                this.RaisePropertyChanged("Запросы");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        public ШаблонОтчетаКолонка[] Колонки {
            get {
                return this.колонкиField;
            }
            set {
                this.колонкиField = value;
                this.RaisePropertyChanged("Колонки");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string НазваниеОтчета {
            get {
                return this.названиеОтчетаField;
            }
            set {
                this.названиеОтчетаField = value;
                this.RaisePropertyChanged("НазваниеОтчета");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool НижнийКолонтитул {
            get {
                return this.нижнийКолонтитулField;
            }
            set {
                this.нижнийКолонтитулField = value;
                this.RaisePropertyChanged("НижнийКолонтитул");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ШаблонОтчетаОриентация ОриентацияСтраницы {
            get {
                return this.ориентацияСтраницыField;
            }
            set {
                this.ориентацияСтраницыField = value;
                this.RaisePropertyChanged("ОриентацияСтраницы");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ФорматОтчета ФорматОтчета {
            get {
                return this.форматОтчетаField;
            }
            set {
                this.форматОтчетаField = value;
                this.RaisePropertyChanged("ФорматОтчета");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ШаблонОтчета.Ориентация", Namespace="http://schemas.datacontract.org/2004/07/RosService.Files")]
    public enum ШаблонОтчетаОриентация {
        
        /// <remarks/>
        Альбом,
        
        /// <remarks/>
        Книга,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Data")]
    public enum ФорматОтчета {
        
        /// <remarks/>
        ПоУмолчанию,
        
        /// <remarks/>
        Xaml,
        
        /// <remarks/>
        Xps,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Query.Параметр", Namespace="http://schemas.datacontract.org/2004/07/RosService.Data")]
    public partial class QueryПараметр : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object значениеField;
        
        private string имяField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public object Значение {
            get {
                return this.значениеField;
            }
            set {
                this.значениеField = value;
                this.RaisePropertyChanged("Значение");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Имя {
            get {
                return this.имяField;
            }
            set {
                this.имяField = value;
                this.RaisePropertyChanged("Имя");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ПолучитьФайлПолностью", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ПолучитьФайлПолностьюRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object id_file;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public RosService.Files.Хранилище хранилище;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        public ПолучитьФайлПолностьюRequest() {
        }
        
        public ПолучитьФайлПолностьюRequest(object id_file, RosService.Files.Хранилище хранилище, string domain) {
            this.id_file = id_file;
            this.хранилище = хранилище;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ПолучитьФайлПолностьюResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ПолучитьФайлПолностьюResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] ПолучитьФайлПолностьюResult;
        
        public ПолучитьФайлПолностьюResponse() {
        }
        
        public ПолучитьФайлПолностьюResponse(byte[] ПолучитьФайлПолностьюResult) {
            this.ПолучитьФайлПолностьюResult = ПолучитьФайлПолностьюResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ПолучитьФайлПолностьюПоНазванию", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ПолучитьФайлПолностьюПоНазваниюRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object id_node;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ИдентификаторФайла;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public RosService.Files.Хранилище хранилище;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        public ПолучитьФайлПолностьюПоНазваниюRequest() {
        }
        
        public ПолучитьФайлПолностьюПоНазваниюRequest(object id_node, string ИдентификаторФайла, RosService.Files.Хранилище хранилище, string domain) {
            this.id_node = id_node;
            this.ИдентификаторФайла = ИдентификаторФайла;
            this.хранилище = хранилище;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ПолучитьФайлПолностьюПоНазваниюResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ПолучитьФайлПолностьюПоНазваниюResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] ПолучитьФайлПолностьюПоНазваниюResult;
        
        public ПолучитьФайлПолностьюПоНазваниюResponse() {
        }
        
        public ПолучитьФайлПолностьюПоНазваниюResponse(byte[] ПолучитьФайлПолностьюПоНазваниюResult) {
            this.ПолучитьФайлПолностьюПоНазваниюResult = ПолучитьФайлПолностьюПоНазваниюResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public decimal id_node;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string user;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ИдентификаторФайла;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ИмяФайла;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Описание;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RosService.Files.Хранилище хранилище;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public UploadRequest() {
        }
        
        public UploadRequest(long Length, string domain, decimal id_node, string user, string ИдентификаторФайла, string ИмяФайла, string Описание, RosService.Files.Хранилище хранилище, System.IO.Stream FileByteStream) {
            this.Length = Length;
            this.domain = domain;
            this.id_node = id_node;
            this.user = user;
            this.ИдентификаторФайла = ИдентификаторФайла;
            this.ИмяФайла = ИмяФайла;
            this.Описание = Описание;
            this.хранилище = хранилище;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadResponce", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadResponce {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal id_file;
        
        public UploadResponce() {
        }
        
        public UploadResponce(decimal id_file) {
            this.id_file = id_file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="СохранитьФайлПолностью", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class СохранитьФайлПолностьюRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object id_node;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ИдентификаторФайла;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ИмяФайла;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Описание;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] stream;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public RosService.Files.Хранилище хранилище;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        public СохранитьФайлПолностьюRequest() {
        }
        
        public СохранитьФайлПолностьюRequest(object id_node, string ИдентификаторФайла, string ИмяФайла, string Описание, byte[] stream, RosService.Files.Хранилище хранилище, string user, string domain) {
            this.id_node = id_node;
            this.ИдентификаторФайла = ИдентификаторФайла;
            this.ИмяФайла = ИмяФайла;
            this.Описание = Описание;
            this.stream = stream;
            this.хранилище = хранилище;
            this.user = user;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="СохранитьФайлПолностьюResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class СохранитьФайлПолностьюResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal СохранитьФайлПолностьюResult;
        
        public СохранитьФайлПолностьюResponse() {
        }
        
        public СохранитьФайлПолностьюResponse(decimal СохранитьФайлПолностьюResult) {
            this.СохранитьФайлПолностьюResult = СохранитьФайлПолностьюResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="СохранитьФайлПолностьюАсинхронно", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class СохранитьФайлПолностьюАсинхронно {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object id_node;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ИдентификаторФайла;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ИмяФайла;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Описание;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] stream;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public RosService.Files.Хранилище хранилище;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        public СохранитьФайлПолностьюАсинхронно() {
        }
        
        public СохранитьФайлПолностьюАсинхронно(object id_node, string ИдентификаторФайла, string ИмяФайла, string Описание, byte[] stream, RosService.Files.Хранилище хранилище, string user, string domain) {
            this.id_node = id_node;
            this.ИдентификаторФайла = ИдентификаторФайла;
            this.ИмяФайла = ИмяФайла;
            this.Описание = Описание;
            this.stream = stream;
            this.хранилище = хранилище;
            this.user = user;
            this.domain = domain;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Data")]
    public enum MimeType {
        
        /// <remarks/>
        НеОпределен,
        
        /// <remarks/>
        Изображение,
        
        /// <remarks/>
        Word,
        
        /// <remarks/>
        Excel,
        
        /// <remarks/>
        Xps,
        
        /// <remarks/>
        Text,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ОтчетRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ОтчетRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string НазваниеОтчета;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Data")]
        public QueryПараметр[] Параметры;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public RosService.Files.ФорматОтчета ФорматОтчета;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        public ОтчетRequest() {
        }
        
        public ОтчетRequest(string НазваниеОтчета, QueryПараметр[] Параметры, RosService.Files.ФорматОтчета ФорматОтчета, string user, string domain) {
            this.НазваниеОтчета = НазваниеОтчета;
            this.Параметры = Параметры;
            this.ФорматОтчета = ФорматОтчета;
            this.user = user;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ОтчетResponce", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ОтчетResponce {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long Length;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RosService.Files.MimeType MimeType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public ОтчетResponce() {
        }
        
        public ОтчетResponce(string FileName, long Length, RosService.Files.MimeType MimeType, System.IO.Stream FileByteStream) {
            this.FileName = FileName;
            this.Length = Length;
            this.MimeType = MimeType;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ОтчетКонструкторRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ОтчетКонструкторRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RosService.Files.ШаблонОтчета Шаблон;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Хранилище;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        public ОтчетКонструкторRequest() {
        }
        
        public ОтчетКонструкторRequest(RosService.Files.ШаблонОтчета Шаблон, string Хранилище, string user, string domain) {
            this.Шаблон = Шаблон;
            this.Хранилище = Хранилище;
            this.user = user;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ОтчетДанныеRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ОтчетДанныеRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string НазваниеОтчета;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Data")]
        public QueryПараметр[] Параметры;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        public ОтчетДанныеRequest() {
        }
        
        public ОтчетДанныеRequest(string НазваниеОтчета, QueryПараметр[] Параметры, string user, string domain) {
            this.НазваниеОтчета = НазваниеОтчета;
            this.Параметры = Параметры;
            this.user = user;
            this.domain = domain;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Files")]
    public enum ImageType {
        
        /// <remarks/>
        Full,
        
        /// <remarks/>
        Thumbnail,
        
        /// <remarks/>
        Resize,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/RosService.Files")]
    public enum ImageFormat {
        
        /// <remarks/>
        Jpg,
        
        /// <remarks/>
        Png,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ПолучитьФайлПросмотр", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ПолучитьФайлПросмотрRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object id_file;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public RosService.Files.ImageType type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int width;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int height;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public RosService.Files.ImageFormat format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public long Качество;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RosService.Files.КонструкторИзображения Конструктор;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        public ПолучитьФайлПросмотрRequest() {
        }
        
        public ПолучитьФайлПросмотрRequest(object id_file, RosService.Files.ImageType type, int width, int height, RosService.Files.ImageFormat format, long Качество, RosService.Files.КонструкторИзображения Конструктор, string domain) {
            this.id_file = id_file;
            this.type = type;
            this.width = width;
            this.height = height;
            this.format = format;
            this.Качество = Качество;
            this.Конструктор = Конструктор;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ПолучитьФайлПросмотрResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ПолучитьФайлПросмотрResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] ПолучитьФайлПросмотрResult;
        
        public ПолучитьФайлПросмотрResponse() {
        }
        
        public ПолучитьФайлПросмотрResponse(byte[] ПолучитьФайлПросмотрResult) {
            this.ПолучитьФайлПросмотрResult = ПолучитьФайлПросмотрResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ПолучитьФайлПросмотрПоНазванию", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ПолучитьФайлПросмотрПоНазваниюRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object id_node;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ИмяФайла;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public RosService.Files.ImageType type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int width;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int height;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public RosService.Files.ImageFormat format;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public long Качество;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RosService.Files.КонструкторИзображения Конструктор;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public RosService.Files.Хранилище хранилище;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string domain;
        
        public ПолучитьФайлПросмотрПоНазваниюRequest() {
        }
        
        public ПолучитьФайлПросмотрПоНазваниюRequest(object id_node, string ИмяФайла, RosService.Files.ImageType type, int width, int height, RosService.Files.ImageFormat format, long Качество, RosService.Files.КонструкторИзображения Конструктор, RosService.Files.Хранилище хранилище, string domain) {
            this.id_node = id_node;
            this.ИмяФайла = ИмяФайла;
            this.type = type;
            this.width = width;
            this.height = height;
            this.format = format;
            this.Качество = Качество;
            this.Конструктор = Конструктор;
            this.хранилище = хранилище;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ПолучитьФайлПросмотрПоНазваниюResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ПолучитьФайлПросмотрПоНазваниюResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] ПолучитьФайлПросмотрПоНазваниюResult;
        
        public ПолучитьФайлПросмотрПоНазваниюResponse() {
        }
        
        public ПолучитьФайлПросмотрПоНазваниюResponse(byte[] ПолучитьФайлПросмотрПоНазваниюResult) {
            this.ПолучитьФайлПросмотрПоНазваниюResult = ПолучитьФайлПросмотрПоНазваниюResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMimeType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMimeTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fileName;
        
        public GetMimeTypeRequest() {
        }
        
        public GetMimeTypeRequest(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMimeTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMimeTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetMimeTypeResult;
        
        public GetMimeTypeResponse() {
        }
        
        public GetMimeTypeResponse(string GetMimeTypeResult) {
            this.GetMimeTypeResult = GetMimeTypeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileChannel : RosService.Files.IFile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileClient : System.ServiceModel.ClientBase<RosService.Files.IFile>, RosService.Files.IFile {
        
        public FileClient() {
        }
        
        public FileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RosService.Files.DownloadResponce RosService.Files.IFile.ПолучитьФайл(RosService.Files.DownloadRequest request) {
            return base.Channel.ПолучитьФайл(request);
        }
        
        public string ПолучитьФайл(string domain, string user, RosService.Files.Хранилище хранилище, decimal id_file, out long Length, out System.IO.Stream FileByteStream) {
            RosService.Files.DownloadRequest inValue = new RosService.Files.DownloadRequest();
            inValue.domain = domain;
            inValue.user = user;
            inValue.хранилище = хранилище;
            inValue.id_file = id_file;
            RosService.Files.DownloadResponce retVal = ((RosService.Files.IFile)(this)).ПолучитьФайл(inValue);
            Length = retVal.Length;
            FileByteStream = retVal.FileByteStream;
            return retVal.FileName;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RosService.Files.ПолучитьФайлПолностьюResponse RosService.Files.IFile.ПолучитьФайлПолностью(RosService.Files.ПолучитьФайлПолностьюRequest request) {
            return base.Channel.ПолучитьФайлПолностью(request);
        }
        
        public byte[] ПолучитьФайлПолностью(object id_file, RosService.Files.Хранилище хранилище, string domain) {
            RosService.Files.ПолучитьФайлПолностьюRequest inValue = new RosService.Files.ПолучитьФайлПолностьюRequest();
            inValue.id_file = id_file;
            inValue.хранилище = хранилище;
            inValue.domain = domain;
            RosService.Files.ПолучитьФайлПолностьюResponse retVal = ((RosService.Files.IFile)(this)).ПолучитьФайлПолностью(inValue);
            return retVal.ПолучитьФайлПолностьюResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RosService.Files.ПолучитьФайлПолностьюПоНазваниюResponse RosService.Files.IFile.ПолучитьФайлПолностьюПоНазванию(RosService.Files.ПолучитьФайлПолностьюПоНазваниюRequest request) {
            return base.Channel.ПолучитьФайлПолностьюПоНазванию(request);
        }
        
        public byte[] ПолучитьФайлПолностьюПоНазванию(object id_node, string ИдентификаторФайла, RosService.Files.Хранилище хранилище, string domain) {
            RosService.Files.ПолучитьФайлПолностьюПоНазваниюRequest inValue = new RosService.Files.ПолучитьФайлПолностьюПоНазваниюRequest();
            inValue.id_node = id_node;
            inValue.ИдентификаторФайла = ИдентификаторФайла;
            inValue.хранилище = хранилище;
            inValue.domain = domain;
            RosService.Files.ПолучитьФайлПолностьюПоНазваниюResponse retVal = ((RosService.Files.IFile)(this)).ПолучитьФайлПолностьюПоНазванию(inValue);
            return retVal.ПолучитьФайлПолностьюПоНазваниюResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RosService.Files.UploadResponce RosService.Files.IFile.СохранитьФайл(RosService.Files.UploadRequest request) {
            return base.Channel.СохранитьФайл(request);
        }
        
        public decimal СохранитьФайл(long Length, string domain, decimal id_node, string user, string ИдентификаторФайла, string ИмяФайла, string Описание, RosService.Files.Хранилище хранилище, System.IO.Stream FileByteStream) {
            RosService.Files.UploadRequest inValue = new RosService.Files.UploadRequest();
            inValue.Length = Length;
            inValue.domain = domain;
            inValue.id_node = id_node;
            inValue.user = user;
            inValue.ИдентификаторФайла = ИдентификаторФайла;
            inValue.ИмяФайла = ИмяФайла;
            inValue.Описание = Описание;
            inValue.хранилище = хранилище;
            inValue.FileByteStream = FileByteStream;
            RosService.Files.UploadResponce retVal = ((RosService.Files.IFile)(this)).СохранитьФайл(inValue);
            return retVal.id_file;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RosService.Files.СохранитьФайлПолностьюResponse RosService.Files.IFile.СохранитьФайлПолностью(RosService.Files.СохранитьФайлПолностьюRequest request) {
            return base.Channel.СохранитьФайлПолностью(request);
        }
        
        public decimal СохранитьФайлПолностью(object id_node, string ИдентификаторФайла, string ИмяФайла, string Описание, byte[] stream, RosService.Files.Хранилище хранилище, string user, string domain) {
            RosService.Files.СохранитьФайлПолностьюRequest inValue = new RosService.Files.СохранитьФайлПолностьюRequest();
            inValue.id_node = id_node;
            inValue.ИдентификаторФайла = ИдентификаторФайла;
            inValue.ИмяФайла = ИмяФайла;
            inValue.Описание = Описание;
            inValue.stream = stream;
            inValue.хранилище = хранилище;
            inValue.user = user;
            inValue.domain = domain;
            RosService.Files.СохранитьФайлПолностьюResponse retVal = ((RosService.Files.IFile)(this)).СохранитьФайлПолностью(inValue);
            return retVal.СохранитьФайлПолностьюResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void RosService.Files.IFile.СохранитьФайлПолностьюАсинхронно(RosService.Files.СохранитьФайлПолностьюАсинхронно request) {
            base.Channel.СохранитьФайлПолностьюАсинхронно(request);
        }
        
        public void СохранитьФайлПолностьюАсинхронно(object id_node, string ИдентификаторФайла, string ИмяФайла, string Описание, byte[] stream, RosService.Files.Хранилище хранилище, string user, string domain) {
            RosService.Files.СохранитьФайлПолностьюАсинхронно inValue = new RosService.Files.СохранитьФайлПолностьюАсинхронно();
            inValue.id_node = id_node;
            inValue.ИдентификаторФайла = ИдентификаторФайла;
            inValue.ИмяФайла = ИмяФайла;
            inValue.Описание = Описание;
            inValue.stream = stream;
            inValue.хранилище = хранилище;
            inValue.user = user;
            inValue.domain = domain;
            ((RosService.Files.IFile)(this)).СохранитьФайлПолностьюАсинхронно(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RosService.Files.ОтчетResponce RosService.Files.IFile.Отчет(RosService.Files.ОтчетRequest request) {
            return base.Channel.Отчет(request);
        }
        
        public string Отчет(string НазваниеОтчета, QueryПараметр[] Параметры, RosService.Files.ФорматОтчета ФорматОтчета, string user, string domain, out long Length, out RosService.Files.MimeType MimeType, out System.IO.Stream FileByteStream) {
            RosService.Files.ОтчетRequest inValue = new RosService.Files.ОтчетRequest();
            inValue.НазваниеОтчета = НазваниеОтчета;
            inValue.Параметры = Параметры;
            inValue.ФорматОтчета = ФорматОтчета;
            inValue.user = user;
            inValue.domain = domain;
            RosService.Files.ОтчетResponce retVal = ((RosService.Files.IFile)(this)).Отчет(inValue);
            Length = retVal.Length;
            MimeType = retVal.MimeType;
            FileByteStream = retVal.FileByteStream;
            return retVal.FileName;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RosService.Files.ОтчетResponce RosService.Files.IFile.ОтчетКонструктор(RosService.Files.ОтчетКонструкторRequest request) {
            return base.Channel.ОтчетКонструктор(request);
        }
        
        public string ОтчетКонструктор(RosService.Files.ШаблонОтчета Шаблон, string Хранилище, string user, string domain, out long Length, out RosService.Files.MimeType MimeType, out System.IO.Stream FileByteStream) {
            RosService.Files.ОтчетКонструкторRequest inValue = new RosService.Files.ОтчетКонструкторRequest();
            inValue.Шаблон = Шаблон;
            inValue.Хранилище = Хранилище;
            inValue.user = user;
            inValue.domain = domain;
            RosService.Files.ОтчетResponce retVal = ((RosService.Files.IFile)(this)).ОтчетКонструктор(inValue);
            Length = retVal.Length;
            MimeType = retVal.MimeType;
            FileByteStream = retVal.FileByteStream;
            return retVal.FileName;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RosService.Files.DownloadResponce RosService.Files.IFile.ОтчетДанные(RosService.Files.ОтчетДанныеRequest request) {
            return base.Channel.ОтчетДанные(request);
        }
        
        public string ОтчетДанные(string НазваниеОтчета, QueryПараметр[] Параметры, string user, string domain, out long Length, out System.IO.Stream FileByteStream) {
            RosService.Files.ОтчетДанныеRequest inValue = new RosService.Files.ОтчетДанныеRequest();
            inValue.НазваниеОтчета = НазваниеОтчета;
            inValue.Параметры = Параметры;
            inValue.user = user;
            inValue.domain = domain;
            RosService.Files.DownloadResponce retVal = ((RosService.Files.IFile)(this)).ОтчетДанные(inValue);
            Length = retVal.Length;
            FileByteStream = retVal.FileByteStream;
            return retVal.FileName;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RosService.Files.ПолучитьФайлПросмотрResponse RosService.Files.IFile.ПолучитьФайлПросмотр(RosService.Files.ПолучитьФайлПросмотрRequest request) {
            return base.Channel.ПолучитьФайлПросмотр(request);
        }
        
        public byte[] ПолучитьФайлПросмотр(object id_file, RosService.Files.ImageType type, int width, int height, RosService.Files.ImageFormat format, long Качество, RosService.Files.КонструкторИзображения Конструктор, string domain) {
            RosService.Files.ПолучитьФайлПросмотрRequest inValue = new RosService.Files.ПолучитьФайлПросмотрRequest();
            inValue.id_file = id_file;
            inValue.type = type;
            inValue.width = width;
            inValue.height = height;
            inValue.format = format;
            inValue.Качество = Качество;
            inValue.Конструктор = Конструктор;
            inValue.domain = domain;
            RosService.Files.ПолучитьФайлПросмотрResponse retVal = ((RosService.Files.IFile)(this)).ПолучитьФайлПросмотр(inValue);
            return retVal.ПолучитьФайлПросмотрResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RosService.Files.ПолучитьФайлПросмотрПоНазваниюResponse RosService.Files.IFile.ПолучитьФайлПросмотрПоНазванию(RosService.Files.ПолучитьФайлПросмотрПоНазваниюRequest request) {
            return base.Channel.ПолучитьФайлПросмотрПоНазванию(request);
        }
        
        public byte[] ПолучитьФайлПросмотрПоНазванию(object id_node, string ИмяФайла, RosService.Files.ImageType type, int width, int height, RosService.Files.ImageFormat format, long Качество, RosService.Files.КонструкторИзображения Конструктор, RosService.Files.Хранилище хранилище, string domain) {
            RosService.Files.ПолучитьФайлПросмотрПоНазваниюRequest inValue = new RosService.Files.ПолучитьФайлПросмотрПоНазваниюRequest();
            inValue.id_node = id_node;
            inValue.ИмяФайла = ИмяФайла;
            inValue.type = type;
            inValue.width = width;
            inValue.height = height;
            inValue.format = format;
            inValue.Качество = Качество;
            inValue.Конструктор = Конструктор;
            inValue.хранилище = хранилище;
            inValue.domain = domain;
            RosService.Files.ПолучитьФайлПросмотрПоНазваниюResponse retVal = ((RosService.Files.IFile)(this)).ПолучитьФайлПросмотрПоНазванию(inValue);
            return retVal.ПолучитьФайлПросмотрПоНазваниюResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RosService.Files.GetMimeTypeResponse RosService.Files.IFile.GetMimeType(RosService.Files.GetMimeTypeRequest request) {
            return base.Channel.GetMimeType(request);
        }
        
        public string GetMimeType(string fileName) {
            RosService.Files.GetMimeTypeRequest inValue = new RosService.Files.GetMimeTypeRequest();
            inValue.fileName = fileName;
            RosService.Files.GetMimeTypeResponse retVal = ((RosService.Files.IFile)(this)).GetMimeType(inValue);
            return retVal.GetMimeTypeResult;
        }
    }
}
