//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1008
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosService.Configuration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteLog", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    [System.SerializableAttribute()]
    public partial class DeleteLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string labelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string label {
            get {
                return this.labelField;
            }
            set {
                if ((object.ReferenceEquals(this.labelField, value) != true)) {
                    this.labelField = value;
                    this.RaisePropertyChanged("label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Type", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    [System.SerializableAttribute()]
    public partial class Type : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DeclaringTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAutoIncrementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReadOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSetDefaultValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RosService.Configuration.MemberTypes MemberTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamespaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReflectedTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RosService.Configuration.RegisterTypes RegisterTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeHashCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ОписаниеField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseType {
            get {
                return this.BaseTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseTypeField, value) != true)) {
                    this.BaseTypeField = value;
                    this.RaisePropertyChanged("BaseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DeclaringType {
            get {
                return this.DeclaringTypeField;
            }
            set {
                if ((this.DeclaringTypeField.Equals(value) != true)) {
                    this.DeclaringTypeField = value;
                    this.RaisePropertyChanged("DeclaringType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashCode {
            get {
                return this.HashCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.HashCodeField, value) != true)) {
                    this.HashCodeField = value;
                    this.RaisePropertyChanged("HashCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAutoIncrement {
            get {
                return this.IsAutoIncrementField;
            }
            set {
                if ((this.IsAutoIncrementField.Equals(value) != true)) {
                    this.IsAutoIncrementField = value;
                    this.RaisePropertyChanged("IsAutoIncrement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReadOnly {
            get {
                return this.IsReadOnlyField;
            }
            set {
                if ((this.IsReadOnlyField.Equals(value) != true)) {
                    this.IsReadOnlyField = value;
                    this.RaisePropertyChanged("IsReadOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSetDefaultValue {
            get {
                return this.IsSetDefaultValueField;
            }
            set {
                if ((this.IsSetDefaultValueField.Equals(value) != true)) {
                    this.IsSetDefaultValueField = value;
                    this.RaisePropertyChanged("IsSetDefaultValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RosService.Configuration.MemberTypes MemberType {
            get {
                return this.MemberTypeField;
            }
            set {
                if ((this.MemberTypeField.Equals(value) != true)) {
                    this.MemberTypeField = value;
                    this.RaisePropertyChanged("MemberType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namespace {
            get {
                return this.NamespaceField;
            }
            set {
                if ((object.ReferenceEquals(this.NamespaceField, value) != true)) {
                    this.NamespaceField = value;
                    this.RaisePropertyChanged("Namespace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReflectedType {
            get {
                return this.ReflectedTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReflectedTypeField, value) != true)) {
                    this.ReflectedTypeField = value;
                    this.RaisePropertyChanged("ReflectedType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RosService.Configuration.RegisterTypes RegisterType {
            get {
                return this.RegisterTypeField;
            }
            set {
                if ((this.RegisterTypeField.Equals(value) != true)) {
                    this.RegisterTypeField = value;
                    this.RaisePropertyChanged("RegisterType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeHashCode {
            get {
                return this.TypeHashCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeHashCodeField, value) != true)) {
                    this.TypeHashCodeField = value;
                    this.RaisePropertyChanged("TypeHashCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Описание {
            get {
                return this.ОписаниеField;
            }
            set {
                if ((object.ReferenceEquals(this.ОписаниеField, value) != true)) {
                    this.ОписаниеField = value;
                    this.RaisePropertyChanged("Описание");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberTypes", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    public enum MemberTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Object = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Int = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bool = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ссылка = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Таблица = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Byte = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterTypes", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    public enum RegisterTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        undefined = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        double_value = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        datetime_value = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        string_value = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        byte_value = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binding", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    [System.SerializableAttribute()]
    public partial class Binding : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string attributeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string controlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyPath {
            get {
                return this.PropertyPathField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyPathField, value) != true)) {
                    this.PropertyPathField = value;
                    this.RaisePropertyChanged("PropertyPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringFormat {
            get {
                return this.StringFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.StringFormatField, value) != true)) {
                    this.StringFormatField = value;
                    this.RaisePropertyChanged("StringFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attribute {
            get {
                return this.attributeField;
            }
            set {
                if ((object.ReferenceEquals(this.attributeField, value) != true)) {
                    this.attributeField = value;
                    this.RaisePropertyChanged("attribute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string control {
            get {
                return this.controlField;
            }
            set {
                if ((object.ReferenceEquals(this.controlField, value) != true)) {
                    this.controlField = value;
                    this.RaisePropertyChanged("control");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string controlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ИмяСобытияField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ИмяФункцииField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string control {
            get {
                return this.controlField;
            }
            set {
                if ((object.ReferenceEquals(this.controlField, value) != true)) {
                    this.controlField = value;
                    this.RaisePropertyChanged("control");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ИмяСобытия {
            get {
                return this.ИмяСобытияField;
            }
            set {
                if ((object.ReferenceEquals(this.ИмяСобытияField, value) != true)) {
                    this.ИмяСобытияField = value;
                    this.RaisePropertyChanged("ИмяСобытия");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ИмяФункции {
            get {
                return this.ИмяФункцииField;
            }
            set {
                if ((object.ReferenceEquals(this.ИмяФункцииField, value) != true)) {
                    this.ИмяФункцииField = value;
                    this.RaisePropertyChanged("ИмяФункции");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Форма", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    [System.SerializableAttribute()]
    public partial class Форма : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RosService.Configuration.Binding[] BindingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RosService.Configuration.Event[] EventsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XamlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ИсходныйКодField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RosService.Configuration.Binding[] Bindings {
            get {
                return this.BindingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BindingsField, value) != true)) {
                    this.BindingsField = value;
                    this.RaisePropertyChanged("Bindings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RosService.Configuration.Event[] Events {
            get {
                return this.EventsField;
            }
            set {
                if ((object.ReferenceEquals(this.EventsField, value) != true)) {
                    this.EventsField = value;
                    this.RaisePropertyChanged("Events");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Xaml {
            get {
                return this.XamlField;
            }
            set {
                if ((object.ReferenceEquals(this.XamlField, value) != true)) {
                    this.XamlField = value;
                    this.RaisePropertyChanged("Xaml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ИсходныйКод {
            get {
                return this.ИсходныйКодField;
            }
            set {
                if ((object.ReferenceEquals(this.ИсходныйКодField, value) != true)) {
                    this.ИсходныйКодField = value;
                    this.RaisePropertyChanged("ИсходныйКод");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="УсловияКопирования", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    public enum УсловияКопирования : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        НеОпределено = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Атрибуты = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Шаблон = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ИсходныйКод = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ЗначенияПоУмолчанию = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Иконка = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ВсеДомены = 32,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ВебСервис", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    [System.SerializableAttribute()]
    public partial class ВебСервис : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamespaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string АдресField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string НазваниеField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ФайлField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namespace {
            get {
                return this.NamespaceField;
            }
            set {
                if ((object.ReferenceEquals(this.NamespaceField, value) != true)) {
                    this.NamespaceField = value;
                    this.RaisePropertyChanged("Namespace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Адрес {
            get {
                return this.АдресField;
            }
            set {
                if ((object.ReferenceEquals(this.АдресField, value) != true)) {
                    this.АдресField = value;
                    this.RaisePropertyChanged("Адрес");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Название {
            get {
                return this.НазваниеField;
            }
            set {
                if ((object.ReferenceEquals(this.НазваниеField, value) != true)) {
                    this.НазваниеField = value;
                    this.RaisePropertyChanged("Название");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Файл {
            get {
                return this.ФайлField;
            }
            set {
                if ((object.ReferenceEquals(this.ФайлField, value) != true)) {
                    this.ФайлField = value;
                    this.RaisePropertyChanged("Файл");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Журнал", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    [System.SerializableAttribute()]
    public partial class Журнал : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ГруппаField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ИмяField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ОписаниеField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Группа {
            get {
                return this.ГруппаField;
            }
            set {
                if ((object.ReferenceEquals(this.ГруппаField, value) != true)) {
                    this.ГруппаField = value;
                    this.RaisePropertyChanged("Группа");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Имя {
            get {
                return this.ИмяField;
            }
            set {
                if ((object.ReferenceEquals(this.ИмяField, value) != true)) {
                    this.ИмяField = value;
                    this.RaisePropertyChanged("Имя");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Описание {
            get {
                return this.ОписаниеField;
            }
            set {
                if ((object.ReferenceEquals(this.ОписаниеField, value) != true)) {
                    this.ОписаниеField = value;
                    this.RaisePropertyChanged("Описание");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Отчет", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    [System.SerializableAttribute()]
    public partial class Отчет : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ГруппаField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ИмяField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ОписаниеField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Группа {
            get {
                return this.ГруппаField;
            }
            set {
                if ((object.ReferenceEquals(this.ГруппаField, value) != true)) {
                    this.ГруппаField = value;
                    this.RaisePropertyChanged("Группа");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Имя {
            get {
                return this.ИмяField;
            }
            set {
                if ((object.ReferenceEquals(this.ИмяField, value) != true)) {
                    this.ИмяField = value;
                    this.RaisePropertyChanged("Имя");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Описание {
            get {
                return this.ОписаниеField;
            }
            set {
                if ((object.ReferenceEquals(this.ОписаниеField, value) != true)) {
                    this.ОписаниеField = value;
                    this.RaisePropertyChanged("Описание");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Справочник", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    [System.SerializableAttribute()]
    public partial class Справочник : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal id_nodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ГруппаField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ИмяField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ОписаниеField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal id_node {
            get {
                return this.id_nodeField;
            }
            set {
                if ((this.id_nodeField.Equals(value) != true)) {
                    this.id_nodeField = value;
                    this.RaisePropertyChanged("id_node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Группа {
            get {
                return this.ГруппаField;
            }
            set {
                if ((object.ReferenceEquals(this.ГруппаField, value) != true)) {
                    this.ГруппаField = value;
                    this.RaisePropertyChanged("Группа");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Имя {
            get {
                return this.ИмяField;
            }
            set {
                if ((object.ReferenceEquals(this.ИмяField, value) != true)) {
                    this.ИмяField = value;
                    this.RaisePropertyChanged("Имя");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Описание {
            get {
                return this.ОписаниеField;
            }
            set {
                if ((object.ReferenceEquals(this.ОписаниеField, value) != true)) {
                    this.ОписаниеField = value;
                    this.RaisePropertyChanged("Описание");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CacheObject", Namespace="http://schemas.datacontract.org/2004/07/RosService.Configuration")]
    [System.SerializableAttribute()]
    public partial class CacheObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<uint> AvgTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PercentCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float PercentTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<uint> AvgTime {
            get {
                return this.AvgTimeField;
            }
            set {
                if ((this.AvgTimeField.Equals(value) != true)) {
                    this.AvgTimeField = value;
                    this.RaisePropertyChanged("AvgTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PercentCount {
            get {
                return this.PercentCountField;
            }
            set {
                if ((this.PercentCountField.Equals(value) != true)) {
                    this.PercentCountField = value;
                    this.RaisePropertyChanged("PercentCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float PercentTime {
            get {
                return this.PercentTimeField;
            }
            set {
                if ((this.PercentTimeField.Equals(value) != true)) {
                    this.PercentTimeField = value;
                    this.RaisePropertyChanged("PercentTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Пользователь", Namespace="http://schemas.datacontract.org/2004/07/RosService.Data")]
    [System.SerializableAttribute()]
    public partial class Пользователь : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal id_nodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ГруппаField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ГруппаРазделField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ИнтерфейсField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ЛогинField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal МестоПоискаField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ПоисковыйАтрибутField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RosService.Configuration.ПраваПользователя ПраваField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] РолиField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ТипField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal id_node {
            get {
                return this.id_nodeField;
            }
            set {
                if ((this.id_nodeField.Equals(value) != true)) {
                    this.id_nodeField = value;
                    this.RaisePropertyChanged("id_node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Группа {
            get {
                return this.ГруппаField;
            }
            set {
                if ((object.ReferenceEquals(this.ГруппаField, value) != true)) {
                    this.ГруппаField = value;
                    this.RaisePropertyChanged("Группа");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ГруппаРаздел {
            get {
                return this.ГруппаРазделField;
            }
            set {
                if ((this.ГруппаРазделField.Equals(value) != true)) {
                    this.ГруппаРазделField = value;
                    this.RaisePropertyChanged("ГруппаРаздел");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Интерфейс {
            get {
                return this.ИнтерфейсField;
            }
            set {
                if ((object.ReferenceEquals(this.ИнтерфейсField, value) != true)) {
                    this.ИнтерфейсField = value;
                    this.RaisePropertyChanged("Интерфейс");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Логин {
            get {
                return this.ЛогинField;
            }
            set {
                if ((object.ReferenceEquals(this.ЛогинField, value) != true)) {
                    this.ЛогинField = value;
                    this.RaisePropertyChanged("Логин");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal МестоПоиска {
            get {
                return this.МестоПоискаField;
            }
            set {
                if ((this.МестоПоискаField.Equals(value) != true)) {
                    this.МестоПоискаField = value;
                    this.RaisePropertyChanged("МестоПоиска");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ПоисковыйАтрибут {
            get {
                return this.ПоисковыйАтрибутField;
            }
            set {
                if ((object.ReferenceEquals(this.ПоисковыйАтрибутField, value) != true)) {
                    this.ПоисковыйАтрибутField = value;
                    this.RaisePropertyChanged("ПоисковыйАтрибут");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RosService.Configuration.ПраваПользователя Права {
            get {
                return this.ПраваField;
            }
            set {
                if ((this.ПраваField.Equals(value) != true)) {
                    this.ПраваField = value;
                    this.RaisePropertyChanged("Права");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Роли {
            get {
                return this.РолиField;
            }
            set {
                if ((object.ReferenceEquals(this.РолиField, value) != true)) {
                    this.РолиField = value;
                    this.RaisePropertyChanged("Роли");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Тип {
            get {
                return this.ТипField;
            }
            set {
                if ((object.ReferenceEquals(this.ТипField, value) != true)) {
                    this.ТипField = value;
                    this.RaisePropertyChanged("Тип");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ПраваПользователя", Namespace="http://schemas.datacontract.org/2004/07/RosService.Data")]
    public enum ПраваПользователя : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Пусто = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ДобавлениеРазделов = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        УдалениеРазделов = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        РедактированиеРазделов = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ПоказатьВсеДерево = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ПоказатьОбъектыСозданныеПользователем = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ПоказатьОбъектыПодструктуры = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        УправлениеПользователями = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ПоказатьОбъектыПоАтрибуту = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        СкрытьРекламу = 512,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ЗапретитьРаботуСПочтой = 1024,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ЗапретитьРаботуСЗадачами = 2048,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ЗапретитьПоиск = 4096,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ЗапретитьРасширенныйПоиск = 8192,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Configuration.IConfiguration")]
    public interface IConfiguration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/УдалитьКешированныеЗначения", ReplyAction="http://tempuri.org/IConfiguration/УдалитьКешированныеЗначенияResponse")]
        void УдалитьКешированныеЗначения(string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/ЖурналУдалений", ReplyAction="http://tempuri.org/IConfiguration/ЖурналУдаленийResponse")]
        RosService.Configuration.DeleteLog[] ЖурналУдалений(string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/ПолучитьТип", ReplyAction="http://tempuri.org/IConfiguration/ПолучитьТипResponse")]
        RosService.Configuration.Type ПолучитьТип(string Имя, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/СписокТипов", ReplyAction="http://tempuri.org/IConfiguration/СписокТиповResponse")]
        RosService.Configuration.Type[] СписокТипов(string[] СписокТиповДанных, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/СписокНаследуемыхТипов", ReplyAction="http://tempuri.org/IConfiguration/СписокНаследуемыхТиповResponse")]
        RosService.Configuration.Type[] СписокНаследуемыхТипов(string ТипДанных, bool ДобавитьБазовыйТип, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/СписокАтрибутов", ReplyAction="http://tempuri.org/IConfiguration/СписокАтрибутовResponse")]
        RosService.Configuration.Type[] СписокАтрибутов(string ТипДанных, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/СписокКатегорий", ReplyAction="http://tempuri.org/IConfiguration/СписокКатегорийResponse")]
        string[] СписокКатегорий(string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/ПолучитьЗначение", ReplyAction="http://tempuri.org/IConfiguration/ПолучитьЗначениеResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.DeleteLog[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.DeleteLog))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Type))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.MemberTypes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.RegisterTypes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Type[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Binding[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Binding))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Event[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Event))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Форма))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.УсловияКопирования))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.ВебСервис[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.ВебСервис))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Журнал[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Журнал))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Отчет[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Отчет))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Справочник[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Справочник))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.CacheObject[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.CacheObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, byte[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Пользователь))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.ПраваПользователя))]
        object ПолучитьЗначение(string Тип, string Атрибут, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/СохранитьЗначение", ReplyAction="http://tempuri.org/IConfiguration/СохранитьЗначениеResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.DeleteLog[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.DeleteLog))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Type))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.MemberTypes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.RegisterTypes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Type[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Binding[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Binding))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Event[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Event))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Форма))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.УсловияКопирования))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.ВебСервис[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.ВебСервис))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Журнал[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Журнал))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Отчет[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Отчет))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Справочник[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Справочник))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.CacheObject[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.CacheObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, byte[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Пользователь))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.ПраваПользователя))]
        void СохранитьЗначение(string Тип, string attribute, object value, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/УдалитьТип", ReplyAction="http://tempuri.org/IConfiguration/УдалитьТипResponse")]
        void УдалитьТип(string ТипДанных, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/УдалитьАтрибут", ReplyAction="http://tempuri.org/IConfiguration/УдалитьАтрибутResponse")]
        void УдалитьАтрибут(string ТипДанных, string Атрибут, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/ПроверитьНаследование", ReplyAction="http://tempuri.org/IConfiguration/ПроверитьНаследованиеResponse")]
        bool ПроверитьНаследование(string БазовыйТип, string Тип, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Binder_СписокСвязей", ReplyAction="http://tempuri.org/IConfiguration/Binder_СписокСвязейResponse")]
        RosService.Configuration.Binding[] Binder_СписокСвязей(string ТипДанных, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Binder_СохранитьСвязь", ReplyAction="http://tempuri.org/IConfiguration/Binder_СохранитьСвязьResponse")]
        void Binder_СохранитьСвязь(string ТипДанных, string attribute, string control, string PropertyPath, string StringFormat, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Binder_УдалитьСвязи", ReplyAction="http://tempuri.org/IConfiguration/Binder_УдалитьСвязиResponse")]
        void Binder_УдалитьСвязи(string ТипДанных, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Event_СписокСобытий", ReplyAction="http://tempuri.org/IConfiguration/Event_СписокСобытийResponse")]
        RosService.Configuration.Event[] Event_СписокСобытий(string ТипДанных, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Event_СохранитьСобытие", ReplyAction="http://tempuri.org/IConfiguration/Event_СохранитьСобытиеResponse")]
        void Event_СохранитьСобытие(string ТипДанных, string control, string ИмяСобытия, string ИмяФункции, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Event_УдалитьСобытие", ReplyAction="http://tempuri.org/IConfiguration/Event_УдалитьСобытиеResponse")]
        void Event_УдалитьСобытие(string ТипДанных, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Процесс_СоздатьПроцесс", ReplyAction="http://tempuri.org/IConfiguration/Процесс_СоздатьПроцессResponse")]
        decimal Процесс_СоздатьПроцесс(string НазваниеПроцесса, string Описание, string Тип, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Процесс_ОбновитьСостояниеПроцесса", ReplyAction="http://tempuri.org/IConfiguration/Процесс_ОбновитьСостояниеПроцессаResponse")]
        void Процесс_ОбновитьСостояниеПроцесса(decimal Процесс, double СостояниеПроцесса, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Процесс_ЗавершитьПроцесс", ReplyAction="http://tempuri.org/IConfiguration/Процесс_ЗавершитьПроцессResponse")]
        void Процесс_ЗавершитьПроцесс(decimal Процесс, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Процесс_ОшибкаВПроцессе", ReplyAction="http://tempuri.org/IConfiguration/Процесс_ОшибкаВПроцессеResponse")]
        void Процесс_ОшибкаВПроцессе(decimal Процесс, string СообщениеОбОшибке, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/ПолучитьФорму", ReplyAction="http://tempuri.org/IConfiguration/ПолучитьФормуResponse")]
        RosService.Configuration.Форма ПолучитьФорму(string ТипДанных, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/КопироватьТипДанных", ReplyAction="http://tempuri.org/IConfiguration/КопироватьТипДанныхResponse")]
        void КопироватьТипДанных(string ТипДанных, string ИзДомена, string КопироватьВ, string КопироватьВДомен, RosService.Configuration.УсловияКопирования УсловияКопирования, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Сервис_ДобавитьВебСервис", ReplyAction="http://tempuri.org/IConfiguration/Сервис_ДобавитьВебСервисResponse")]
        decimal Сервис_ДобавитьВебСервис(string Адрес, string Название, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Сервис_СписокВебСервисов", ReplyAction="http://tempuri.org/IConfiguration/Сервис_СписокВебСервисовResponse")]
        RosService.Configuration.ВебСервис[] Сервис_СписокВебСервисов(string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/ДобавитьТип", ReplyAction="http://tempuri.org/IConfiguration/ДобавитьТипResponse")]
        string ДобавитьТип(decimal Номер, string Имя, string Описание, string Категория, string БазовыйТип, bool IsМассив, bool ОбновитьКонфигурацию, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/ДобавитьАтрибут", ReplyAction="http://tempuri.org/IConfiguration/ДобавитьАтрибутResponse")]
        void ДобавитьАтрибут(string ТипДанных, string Атрибут, bool ОбновитьКонфигурацию, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/ОписаниеВИмя", ReplyAction="http://tempuri.org/IConfiguration/ОписаниеВИмяResponse")]
        string ОписаниеВИмя(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/КомпилироватьКонфигурацию", ReplyAction="http://tempuri.org/IConfiguration/КомпилироватьКонфигурациюResponse")]
        void КомпилироватьКонфигурацию(string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/СписокДоменов", ReplyAction="http://tempuri.org/IConfiguration/СписокДоменовResponse")]
        string[] СписокДоменов();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConfiguration/ЖурналСобытийДобавитьОшибку")]
        void ЖурналСобытийДобавитьОшибку(string Message, string StackTrace, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConfiguration/ОтправитьИнструкцию")]
        void ОтправитьИнструкцию(decimal id_user, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/ОтправитьПисьмоВТехническуюПоддержку", ReplyAction="http://tempuri.org/IConfiguration/ОтправитьПисьмоВТехническуюПоддержкуResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.DeleteLog[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.DeleteLog))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Type))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.MemberTypes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.RegisterTypes))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Type[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Binding[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Binding))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Event[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Event))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Форма))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.УсловияКопирования))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.ВебСервис[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.ВебСервис))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Журнал[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Журнал))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Отчет[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Отчет))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Справочник[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Справочник))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.CacheObject[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.CacheObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, byte[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.Пользователь))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Configuration.ПраваПользователя))]
        decimal ОтправитьПисьмоВТехническуюПоддержку(string ИмяДомена, string ОтКого, string ТемаСообщения, string ТекстСообщения, object СрокРеализации, bool Важно, System.Collections.Generic.Dictionary<string, byte[]> СписокФайлов, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/ПолучитьIpАдресСоединения", ReplyAction="http://tempuri.org/IConfiguration/ПолучитьIpАдресСоединенияResponse")]
        string ПолучитьIpАдресСоединения();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/СписокЖурналов", ReplyAction="http://tempuri.org/IConfiguration/СписокЖурналовResponse")]
        RosService.Configuration.Журнал[] СписокЖурналов(string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/СписокОтчетов", ReplyAction="http://tempuri.org/IConfiguration/СписокОтчетовResponse")]
        RosService.Configuration.Отчет[] СписокОтчетов(string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/СписокСправочников", ReplyAction="http://tempuri.org/IConfiguration/СписокСправочниковResponse")]
        RosService.Configuration.Справочник[] СписокСправочников(string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Авторизация", ReplyAction="http://tempuri.org/IConfiguration/АвторизацияResponse")]
        RosService.Configuration.Пользователь Авторизация(string UserName, string Password, bool ЗаписатьВЖурнал, string domain);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConfiguration/АвторизацияПродлитьСессиюПользователя")]
        void АвторизацияПродлитьСессиюПользователя(decimal СсылкаНаПользователя, System.TimeSpan ВремяСесси, string domain);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IConfiguration/АвторизацияБлокировки")]
        void АвторизацияБлокировки(bool Выключить);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/Ping", ReplyAction="http://tempuri.org/IConfiguration/PingResponse")]
        void Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/СписокКешированныхОбъектов", ReplyAction="http://tempuri.org/IConfiguration/СписокКешированныхОбъектовResponse")]
        RosService.Configuration.CacheObject[] СписокКешированныхОбъектов(string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfiguration/УдалитьКешированныеОбъекты", ReplyAction="http://tempuri.org/IConfiguration/УдалитьКешированныеОбъектыResponse")]
        void УдалитьКешированныеОбъекты(string[] items, string user, string domain);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfigurationChannel : RosService.Configuration.IConfiguration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationClient : System.ServiceModel.ClientBase<RosService.Configuration.IConfiguration>, RosService.Configuration.IConfiguration {
        
        public ConfigurationClient() {
        }
        
        public ConfigurationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void УдалитьКешированныеЗначения(string user, string domain) {
            base.Channel.УдалитьКешированныеЗначения(user, domain);
        }
        
        public RosService.Configuration.DeleteLog[] ЖурналУдалений(string domain) {
            return base.Channel.ЖурналУдалений(domain);
        }
        
        public RosService.Configuration.Type ПолучитьТип(string Имя, string domain) {
            return base.Channel.ПолучитьТип(Имя, domain);
        }
        
        public RosService.Configuration.Type[] СписокТипов(string[] СписокТиповДанных, string domain) {
            return base.Channel.СписокТипов(СписокТиповДанных, domain);
        }
        
        public RosService.Configuration.Type[] СписокНаследуемыхТипов(string ТипДанных, bool ДобавитьБазовыйТип, string domain) {
            return base.Channel.СписокНаследуемыхТипов(ТипДанных, ДобавитьБазовыйТип, domain);
        }
        
        public RosService.Configuration.Type[] СписокАтрибутов(string ТипДанных, string domain) {
            return base.Channel.СписокАтрибутов(ТипДанных, domain);
        }
        
        public string[] СписокКатегорий(string domain) {
            return base.Channel.СписокКатегорий(domain);
        }
        
        public object ПолучитьЗначение(string Тип, string Атрибут, string domain) {
            return base.Channel.ПолучитьЗначение(Тип, Атрибут, domain);
        }
        
        public void СохранитьЗначение(string Тип, string attribute, object value, string domain) {
            base.Channel.СохранитьЗначение(Тип, attribute, value, domain);
        }
        
        public void УдалитьТип(string ТипДанных, string domain) {
            base.Channel.УдалитьТип(ТипДанных, domain);
        }
        
        public void УдалитьАтрибут(string ТипДанных, string Атрибут, string domain) {
            base.Channel.УдалитьАтрибут(ТипДанных, Атрибут, domain);
        }
        
        public bool ПроверитьНаследование(string БазовыйТип, string Тип, string user, string domain) {
            return base.Channel.ПроверитьНаследование(БазовыйТип, Тип, user, domain);
        }
        
        public RosService.Configuration.Binding[] Binder_СписокСвязей(string ТипДанных, string domain) {
            return base.Channel.Binder_СписокСвязей(ТипДанных, domain);
        }
        
        public void Binder_СохранитьСвязь(string ТипДанных, string attribute, string control, string PropertyPath, string StringFormat, string domain) {
            base.Channel.Binder_СохранитьСвязь(ТипДанных, attribute, control, PropertyPath, StringFormat, domain);
        }
        
        public void Binder_УдалитьСвязи(string ТипДанных, string domain) {
            base.Channel.Binder_УдалитьСвязи(ТипДанных, domain);
        }
        
        public RosService.Configuration.Event[] Event_СписокСобытий(string ТипДанных, string domain) {
            return base.Channel.Event_СписокСобытий(ТипДанных, domain);
        }
        
        public void Event_СохранитьСобытие(string ТипДанных, string control, string ИмяСобытия, string ИмяФункции, string domain) {
            base.Channel.Event_СохранитьСобытие(ТипДанных, control, ИмяСобытия, ИмяФункции, domain);
        }
        
        public void Event_УдалитьСобытие(string ТипДанных, string domain) {
            base.Channel.Event_УдалитьСобытие(ТипДанных, domain);
        }
        
        public decimal Процесс_СоздатьПроцесс(string НазваниеПроцесса, string Описание, string Тип, string user, string domain) {
            return base.Channel.Процесс_СоздатьПроцесс(НазваниеПроцесса, Описание, Тип, user, domain);
        }
        
        public void Процесс_ОбновитьСостояниеПроцесса(decimal Процесс, double СостояниеПроцесса, string domain) {
            base.Channel.Процесс_ОбновитьСостояниеПроцесса(Процесс, СостояниеПроцесса, domain);
        }
        
        public void Процесс_ЗавершитьПроцесс(decimal Процесс, string domain) {
            base.Channel.Процесс_ЗавершитьПроцесс(Процесс, domain);
        }
        
        public void Процесс_ОшибкаВПроцессе(decimal Процесс, string СообщениеОбОшибке, string domain) {
            base.Channel.Процесс_ОшибкаВПроцессе(Процесс, СообщениеОбОшибке, domain);
        }
        
        public RosService.Configuration.Форма ПолучитьФорму(string ТипДанных, string domain) {
            return base.Channel.ПолучитьФорму(ТипДанных, domain);
        }
        
        public void КопироватьТипДанных(string ТипДанных, string ИзДомена, string КопироватьВ, string КопироватьВДомен, RosService.Configuration.УсловияКопирования УсловияКопирования, string user, string domain) {
            base.Channel.КопироватьТипДанных(ТипДанных, ИзДомена, КопироватьВ, КопироватьВДомен, УсловияКопирования, user, domain);
        }
        
        public decimal Сервис_ДобавитьВебСервис(string Адрес, string Название, string user, string domain) {
            return base.Channel.Сервис_ДобавитьВебСервис(Адрес, Название, user, domain);
        }
        
        public RosService.Configuration.ВебСервис[] Сервис_СписокВебСервисов(string domain) {
            return base.Channel.Сервис_СписокВебСервисов(domain);
        }
        
        public string ДобавитьТип(decimal Номер, string Имя, string Описание, string Категория, string БазовыйТип, bool IsМассив, bool ОбновитьКонфигурацию, string user, string domain) {
            return base.Channel.ДобавитьТип(Номер, Имя, Описание, Категория, БазовыйТип, IsМассив, ОбновитьКонфигурацию, user, domain);
        }
        
        public void ДобавитьАтрибут(string ТипДанных, string Атрибут, bool ОбновитьКонфигурацию, string user, string domain) {
            base.Channel.ДобавитьАтрибут(ТипДанных, Атрибут, ОбновитьКонфигурацию, user, domain);
        }
        
        public string ОписаниеВИмя(string value) {
            return base.Channel.ОписаниеВИмя(value);
        }
        
        public void КомпилироватьКонфигурацию(string domain) {
            base.Channel.КомпилироватьКонфигурацию(domain);
        }
        
        public string[] СписокДоменов() {
            return base.Channel.СписокДоменов();
        }
        
        public void ЖурналСобытийДобавитьОшибку(string Message, string StackTrace, string user, string domain) {
            base.Channel.ЖурналСобытийДобавитьОшибку(Message, StackTrace, user, domain);
        }
        
        public void ОтправитьИнструкцию(decimal id_user, string user, string domain) {
            base.Channel.ОтправитьИнструкцию(id_user, user, domain);
        }
        
        public decimal ОтправитьПисьмоВТехническуюПоддержку(string ИмяДомена, string ОтКого, string ТемаСообщения, string ТекстСообщения, object СрокРеализации, bool Важно, System.Collections.Generic.Dictionary<string, byte[]> СписокФайлов, string user) {
            return base.Channel.ОтправитьПисьмоВТехническуюПоддержку(ИмяДомена, ОтКого, ТемаСообщения, ТекстСообщения, СрокРеализации, Важно, СписокФайлов, user);
        }
        
        public string ПолучитьIpАдресСоединения() {
            return base.Channel.ПолучитьIpАдресСоединения();
        }
        
        public RosService.Configuration.Журнал[] СписокЖурналов(string user, string domain) {
            return base.Channel.СписокЖурналов(user, domain);
        }
        
        public RosService.Configuration.Отчет[] СписокОтчетов(string user, string domain) {
            return base.Channel.СписокОтчетов(user, domain);
        }
        
        public RosService.Configuration.Справочник[] СписокСправочников(string user, string domain) {
            return base.Channel.СписокСправочников(user, domain);
        }
        
        public RosService.Configuration.Пользователь Авторизация(string UserName, string Password, bool ЗаписатьВЖурнал, string domain) {
            return base.Channel.Авторизация(UserName, Password, ЗаписатьВЖурнал, domain);
        }
        
        public void АвторизацияПродлитьСессиюПользователя(decimal СсылкаНаПользователя, System.TimeSpan ВремяСесси, string domain) {
            base.Channel.АвторизацияПродлитьСессиюПользователя(СсылкаНаПользователя, ВремяСесси, domain);
        }
        
        public void АвторизацияБлокировки(bool Выключить) {
            base.Channel.АвторизацияБлокировки(Выключить);
        }
        
        public void Ping() {
            base.Channel.Ping();
        }
        
        public RosService.Configuration.CacheObject[] СписокКешированныхОбъектов(string user, string domain) {
            return base.Channel.СписокКешированныхОбъектов(user, domain);
        }
        
        public void УдалитьКешированныеОбъекты(string[] items, string user, string domain) {
            base.Channel.УдалитьКешированныеОбъекты(items, user, domain);
        }
    }
}
