//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1008
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosService.Finance {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="НапралениеПлатежа", Namespace="http://schemas.datacontract.org/2004/07/RosService.Finance")]
    public enum НапралениеПлатежа : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Приход = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Расход = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="СтавкаНдс", Namespace="http://schemas.datacontract.org/2004/07/RosService.Finance")]
    public enum СтавкаНдс : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        БезНДС = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        НДС0 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        НДС18 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        НДС18_118 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        НДС10 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        НДС10_110 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        НДС20 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        НДС20_120 = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ФорматЧислаПрописью", Namespace="http://schemas.datacontract.org/2004/07/RosService.Finance")]
    public enum ФорматЧислаПрописью : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Число = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Рубли = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Доллар = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Евро = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        РублиБезКопеек = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Инвентаризация", Namespace="http://schemas.datacontract.org/2004/07/RosService.Finance")]
    [System.SerializableAttribute()]
    public partial class Инвентаризация : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal КоличествоНаСкладеField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal КоличествоОстатокField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal КоличествоПроданоField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal СуммаПроданоField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ТоварField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal КоличествоНаСкладе {
            get {
                return this.КоличествоНаСкладеField;
            }
            set {
                if ((this.КоличествоНаСкладеField.Equals(value) != true)) {
                    this.КоличествоНаСкладеField = value;
                    this.RaisePropertyChanged("КоличествоНаСкладе");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal КоличествоОстаток {
            get {
                return this.КоличествоОстатокField;
            }
            set {
                if ((this.КоличествоОстатокField.Equals(value) != true)) {
                    this.КоличествоОстатокField = value;
                    this.RaisePropertyChanged("КоличествоОстаток");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal КоличествоПродано {
            get {
                return this.КоличествоПроданоField;
            }
            set {
                if ((this.КоличествоПроданоField.Equals(value) != true)) {
                    this.КоличествоПроданоField = value;
                    this.RaisePropertyChanged("КоличествоПродано");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal СуммаПродано {
            get {
                return this.СуммаПроданоField;
            }
            set {
                if ((this.СуммаПроданоField.Equals(value) != true)) {
                    this.СуммаПроданоField = value;
                    this.RaisePropertyChanged("СуммаПродано");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Товар {
            get {
                return this.ТоварField;
            }
            set {
                if ((this.ТоварField.Equals(value) != true)) {
                    this.ТоварField = value;
                    this.RaisePropertyChanged("Товар");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Finance.IFinance")]
    public interface IFinance {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ДобавитьПлатеж", ReplyAction="http://tempuri.org/IFinance/ДобавитьПлатежResponse")]
        decimal ДобавитьПлатеж(RosService.Finance.НапралениеПлатежа НапралениеПлатежа, decimal СсылкаНаКонтрагента, decimal СсылкаНаДоговор, string СтатьяДвиженияСредств, System.DateTime ДатаПлатежа, decimal СуммаПлатежа, string СпособОплаты, string НазначениеПлатежа, RosService.Finance.СтавкаНдс СтавкаНдс, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ДобавитьВнутреннийПеревод", ReplyAction="http://tempuri.org/IFinance/ДобавитьВнутреннийПереводResponse")]
        decimal ДобавитьВнутреннийПеревод(RosService.Finance.НапралениеПлатежа НапралениеПлатежа, decimal СсылкаНаКонтрагента, decimal СсылкаНаОбъект, string СтатьяДвиженияДенежныхСредств, System.DateTime ДатаПлатежа, decimal СуммаПлатежа, string НазначениеПлатежа, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ДобавитьВнутреннийПереводНаСчет", ReplyAction="http://tempuri.org/IFinance/ДобавитьВнутреннийПереводНаСчетResponse")]
        decimal ДобавитьВнутреннийПереводНаСчет(string НазваниеСчета, RosService.Finance.НапралениеПлатежа НапралениеПлатежа, decimal СсылкаНаКонтрагента, decimal СсылкаНаОбъект, string СтатьяДвиженияДенежныхСредств, System.DateTime ДатаПлатежа, decimal СуммаПлатежа, string НазначениеПлатежа, string ТипДокумента, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/УдалитьВнутреннийПеревод", ReplyAction="http://tempuri.org/IFinance/УдалитьВнутреннийПереводResponse")]
        void УдалитьВнутреннийПеревод(decimal Платеж, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ВыводСредств", ReplyAction="http://tempuri.org/IFinance/ВыводСредствResponse")]
        decimal ВыводСредств(decimal id_client, System.DateTime Дата, decimal Сумма, string СпособОплаты, string НазначениеПлатежа, bool УдерживатьНДФЛ, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ВыводСредствСоСчета", ReplyAction="http://tempuri.org/IFinance/ВыводСредствСоСчетаResponse")]
        decimal ВыводСредствСоСчета(string НазваниеСчета, decimal СсылкаНаКонтрагента, System.DateTime Дата, decimal Сумма, string СпособОплаты, string НазначениеПлатежа, bool УдерживатьНДФЛ, string ТипДокумента, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ПеревестиСредства", ReplyAction="http://tempuri.org/IFinance/ПеревестиСредстваResponse")]
        void ПеревестиСредства(decimal Отправитель, decimal Получатель, decimal Сумма, string Примечание, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ПеревестиСредстваСоСчета", ReplyAction="http://tempuri.org/IFinance/ПеревестиСредстваСоСчетаResponse")]
        void ПеревестиСредстваСоСчета(string НазваниеСчета, decimal Отправитель, decimal Получатель, decimal Сумма, string Примечание, string ТипДокумента, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/РегистрацияКлиента", ReplyAction="http://tempuri.org/IFinance/РегистрацияКлиентаResponse")]
        decimal РегистрацияКлиента(decimal СсылкаНаМестоАгента, decimal РегиональныйПредставитель, string ВидКонтрагента, string СтатусКонтрагента, string Фамилия, string Имя, string Отчество, string Компания, string Почта, string Пароль, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ПополнитьСчет", ReplyAction="http://tempuri.org/IFinance/ПополнитьСчетResponse")]
        void ПополнитьСчет(string НазваниеСчета, decimal Получатель, decimal СсылкаНаОбъект, System.DateTime Дата, decimal Сумма, string Примечание, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/СписатьСоСчета", ReplyAction="http://tempuri.org/IFinance/СписатьСоСчетаResponse")]
        void СписатьСоСчета(string НазваниеСчета, decimal Получатель, decimal СсылкаНаОбъект, System.DateTime Дата, decimal Сумма, string Примечание, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ПеревестиСоСчета", ReplyAction="http://tempuri.org/IFinance/ПеревестиСоСчетаResponse")]
        void ПеревестиСоСчета(string НазваниеСчета, decimal Отправитель, decimal Получатель, decimal Сумма, string Примечание, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/УдалитьСоСчета", ReplyAction="http://tempuri.org/IFinance/УдалитьСоСчетаResponse")]
        void УдалитьСоСчета(string НазваниеСчета, decimal Получатель, string[] guid, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ОбновитьОстаткиНаСчетах", ReplyAction="http://tempuri.org/IFinance/ОбновитьОстаткиНаСчетахResponse")]
        void ОбновитьОстаткиНаСчетах(string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ОбновитьСведенияКонтрагента", ReplyAction="http://tempuri.org/IFinance/ОбновитьСведенияКонтрагентаResponse")]
        void ОбновитьСведенияКонтрагента(decimal Контрагент, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ОбновитьОстаткиНаВнутреннихСчетах", ReplyAction="http://tempuri.org/IFinance/ОбновитьОстаткиНаВнутреннихСчетахResponse")]
        void ОбновитьОстаткиНаВнутреннихСчетах(string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ПроверитьБанковскиеРеквизитыКонтрагента", ReplyAction="http://tempuri.org/IFinance/ПроверитьБанковскиеРеквизитыКонтрагентаResponse")]
        void ПроверитьБанковскиеРеквизитыКонтрагента(decimal Контрагент, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ПроверитьБанковскиеРеквизиты", ReplyAction="http://tempuri.org/IFinance/ПроверитьБанковскиеРеквизитыResponse")]
        void ПроверитьБанковскиеРеквизиты(string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/НДС", ReplyAction="http://tempuri.org/IFinance/НДСResponse")]
        decimal НДС(string СтавкаНдс);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ЧислоПрописью", ReplyAction="http://tempuri.org/IFinance/ЧислоПрописьюResponse")]
        string ЧислоПрописью(double Число, RosService.Finance.ФорматЧислаПрописью ФорматЧислаПрописью);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFinance/ИнвентаризацияПродукцииНаСкладе")]
        void ИнвентаризацияПродукцииНаСкладе(decimal[] Склады, System.DateTime ДатаИнвентаризации, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinance/ИнвентаризацияПродукцииНаСкладеТаблица", ReplyAction="http://tempuri.org/IFinance/ИнвентаризацияПродукцииНаСкладеТаблицаResponse")]
        RosService.Finance.Инвентаризация[] ИнвентаризацияПродукцииНаСкладеТаблица(decimal Склад, System.DateTime ДатаИнвентаризации, string user, string domain);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinanceChannel : RosService.Finance.IFinance, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinanceClient : System.ServiceModel.ClientBase<RosService.Finance.IFinance>, RosService.Finance.IFinance {
        
        public FinanceClient() {
        }
        
        public FinanceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinanceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal ДобавитьПлатеж(RosService.Finance.НапралениеПлатежа НапралениеПлатежа, decimal СсылкаНаКонтрагента, decimal СсылкаНаДоговор, string СтатьяДвиженияСредств, System.DateTime ДатаПлатежа, decimal СуммаПлатежа, string СпособОплаты, string НазначениеПлатежа, RosService.Finance.СтавкаНдс СтавкаНдс, string user, string domain) {
            return base.Channel.ДобавитьПлатеж(НапралениеПлатежа, СсылкаНаКонтрагента, СсылкаНаДоговор, СтатьяДвиженияСредств, ДатаПлатежа, СуммаПлатежа, СпособОплаты, НазначениеПлатежа, СтавкаНдс, user, domain);
        }
        
        public decimal ДобавитьВнутреннийПеревод(RosService.Finance.НапралениеПлатежа НапралениеПлатежа, decimal СсылкаНаКонтрагента, decimal СсылкаНаОбъект, string СтатьяДвиженияДенежныхСредств, System.DateTime ДатаПлатежа, decimal СуммаПлатежа, string НазначениеПлатежа, string user, string domain) {
            return base.Channel.ДобавитьВнутреннийПеревод(НапралениеПлатежа, СсылкаНаКонтрагента, СсылкаНаОбъект, СтатьяДвиженияДенежныхСредств, ДатаПлатежа, СуммаПлатежа, НазначениеПлатежа, user, domain);
        }
        
        public decimal ДобавитьВнутреннийПереводНаСчет(string НазваниеСчета, RosService.Finance.НапралениеПлатежа НапралениеПлатежа, decimal СсылкаНаКонтрагента, decimal СсылкаНаОбъект, string СтатьяДвиженияДенежныхСредств, System.DateTime ДатаПлатежа, decimal СуммаПлатежа, string НазначениеПлатежа, string ТипДокумента, string user, string domain) {
            return base.Channel.ДобавитьВнутреннийПереводНаСчет(НазваниеСчета, НапралениеПлатежа, СсылкаНаКонтрагента, СсылкаНаОбъект, СтатьяДвиженияДенежныхСредств, ДатаПлатежа, СуммаПлатежа, НазначениеПлатежа, ТипДокумента, user, domain);
        }
        
        public void УдалитьВнутреннийПеревод(decimal Платеж, string user, string domain) {
            base.Channel.УдалитьВнутреннийПеревод(Платеж, user, domain);
        }
        
        public decimal ВыводСредств(decimal id_client, System.DateTime Дата, decimal Сумма, string СпособОплаты, string НазначениеПлатежа, bool УдерживатьНДФЛ, string user, string domain) {
            return base.Channel.ВыводСредств(id_client, Дата, Сумма, СпособОплаты, НазначениеПлатежа, УдерживатьНДФЛ, user, domain);
        }
        
        public decimal ВыводСредствСоСчета(string НазваниеСчета, decimal СсылкаНаКонтрагента, System.DateTime Дата, decimal Сумма, string СпособОплаты, string НазначениеПлатежа, bool УдерживатьНДФЛ, string ТипДокумента, string user, string domain) {
            return base.Channel.ВыводСредствСоСчета(НазваниеСчета, СсылкаНаКонтрагента, Дата, Сумма, СпособОплаты, НазначениеПлатежа, УдерживатьНДФЛ, ТипДокумента, user, domain);
        }
        
        public void ПеревестиСредства(decimal Отправитель, decimal Получатель, decimal Сумма, string Примечание, string user, string domain) {
            base.Channel.ПеревестиСредства(Отправитель, Получатель, Сумма, Примечание, user, domain);
        }
        
        public void ПеревестиСредстваСоСчета(string НазваниеСчета, decimal Отправитель, decimal Получатель, decimal Сумма, string Примечание, string ТипДокумента, string user, string domain) {
            base.Channel.ПеревестиСредстваСоСчета(НазваниеСчета, Отправитель, Получатель, Сумма, Примечание, ТипДокумента, user, domain);
        }
        
        public decimal РегистрацияКлиента(decimal СсылкаНаМестоАгента, decimal РегиональныйПредставитель, string ВидКонтрагента, string СтатусКонтрагента, string Фамилия, string Имя, string Отчество, string Компания, string Почта, string Пароль, string user, string domain) {
            return base.Channel.РегистрацияКлиента(СсылкаНаМестоАгента, РегиональныйПредставитель, ВидКонтрагента, СтатусКонтрагента, Фамилия, Имя, Отчество, Компания, Почта, Пароль, user, domain);
        }
        
        public void ПополнитьСчет(string НазваниеСчета, decimal Получатель, decimal СсылкаНаОбъект, System.DateTime Дата, decimal Сумма, string Примечание, string user, string domain) {
            base.Channel.ПополнитьСчет(НазваниеСчета, Получатель, СсылкаНаОбъект, Дата, Сумма, Примечание, user, domain);
        }
        
        public void СписатьСоСчета(string НазваниеСчета, decimal Получатель, decimal СсылкаНаОбъект, System.DateTime Дата, decimal Сумма, string Примечание, string user, string domain) {
            base.Channel.СписатьСоСчета(НазваниеСчета, Получатель, СсылкаНаОбъект, Дата, Сумма, Примечание, user, domain);
        }
        
        public void ПеревестиСоСчета(string НазваниеСчета, decimal Отправитель, decimal Получатель, decimal Сумма, string Примечание, string user, string domain) {
            base.Channel.ПеревестиСоСчета(НазваниеСчета, Отправитель, Получатель, Сумма, Примечание, user, domain);
        }
        
        public void УдалитьСоСчета(string НазваниеСчета, decimal Получатель, string[] guid, string user, string domain) {
            base.Channel.УдалитьСоСчета(НазваниеСчета, Получатель, guid, user, domain);
        }
        
        public void ОбновитьОстаткиНаСчетах(string user, string domain) {
            base.Channel.ОбновитьОстаткиНаСчетах(user, domain);
        }
        
        public void ОбновитьСведенияКонтрагента(decimal Контрагент, string user, string domain) {
            base.Channel.ОбновитьСведенияКонтрагента(Контрагент, user, domain);
        }
        
        public void ОбновитьОстаткиНаВнутреннихСчетах(string user, string domain) {
            base.Channel.ОбновитьОстаткиНаВнутреннихСчетах(user, domain);
        }
        
        public void ПроверитьБанковскиеРеквизитыКонтрагента(decimal Контрагент, string user, string domain) {
            base.Channel.ПроверитьБанковскиеРеквизитыКонтрагента(Контрагент, user, domain);
        }
        
        public void ПроверитьБанковскиеРеквизиты(string user, string domain) {
            base.Channel.ПроверитьБанковскиеРеквизиты(user, domain);
        }
        
        public decimal НДС(string СтавкаНдс) {
            return base.Channel.НДС(СтавкаНдс);
        }
        
        public string ЧислоПрописью(double Число, RosService.Finance.ФорматЧислаПрописью ФорматЧислаПрописью) {
            return base.Channel.ЧислоПрописью(Число, ФорматЧислаПрописью);
        }
        
        public void ИнвентаризацияПродукцииНаСкладе(decimal[] Склады, System.DateTime ДатаИнвентаризации, string user, string domain) {
            base.Channel.ИнвентаризацияПродукцииНаСкладе(Склады, ДатаИнвентаризации, user, domain);
        }
        
        public RosService.Finance.Инвентаризация[] ИнвентаризацияПродукцииНаСкладеТаблица(decimal Склад, System.DateTime ДатаИнвентаризации, string user, string domain) {
            return base.Channel.ИнвентаризацияПродукцииНаСкладеТаблица(Склад, ДатаИнвентаризации, user, domain);
        }
    }
}
