//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1008
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosService.Services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="БанкСведения", Namespace="http://schemas.datacontract.org/2004/07/RosService.Services")]
    [System.SerializableAttribute()]
    public partial class БанкСведения : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string АдресField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string БИКField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ГородField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string КорСчетField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string НазваниеField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Адрес {
            get {
                return this.АдресField;
            }
            set {
                if ((object.ReferenceEquals(this.АдресField, value) != true)) {
                    this.АдресField = value;
                    this.RaisePropertyChanged("Адрес");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string БИК {
            get {
                return this.БИКField;
            }
            set {
                if ((object.ReferenceEquals(this.БИКField, value) != true)) {
                    this.БИКField = value;
                    this.RaisePropertyChanged("БИК");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Город {
            get {
                return this.ГородField;
            }
            set {
                if ((object.ReferenceEquals(this.ГородField, value) != true)) {
                    this.ГородField = value;
                    this.RaisePropertyChanged("Город");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string КорСчет {
            get {
                return this.КорСчетField;
            }
            set {
                if ((object.ReferenceEquals(this.КорСчетField, value) != true)) {
                    this.КорСчетField = value;
                    this.RaisePropertyChanged("КорСчет");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Название {
            get {
                return this.НазваниеField;
            }
            set {
                if ((object.ReferenceEquals(this.НазваниеField, value) != true)) {
                    this.НазваниеField = value;
                    this.RaisePropertyChanged("Название");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="СообщенияПользователя", Namespace="http://schemas.datacontract.org/2004/07/RosService.Services")]
    [System.SerializableAttribute()]
    public partial class СообщенияПользователя : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal id_nodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int КоличествоField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal id_node {
            get {
                return this.id_nodeField;
            }
            set {
                if ((this.id_nodeField.Equals(value) != true)) {
                    this.id_nodeField = value;
                    this.RaisePropertyChanged("id_node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Количество {
            get {
                return this.КоличествоField;
            }
            set {
                if ((this.КоличествоField.Equals(value) != true)) {
                    this.КоличествоField = value;
                    this.RaisePropertyChanged("Количество");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="СведенияПользователя", Namespace="http://schemas.datacontract.org/2004/07/RosService.Services")]
    [System.SerializableAttribute()]
    public partial class СведенияПользователя : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal id_nodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ВСетиField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ГруппаField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string НазваниеОбъектаField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> СсылкаНаАватарField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal id_node {
            get {
                return this.id_nodeField;
            }
            set {
                if ((this.id_nodeField.Equals(value) != true)) {
                    this.id_nodeField = value;
                    this.RaisePropertyChanged("id_node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ВСети {
            get {
                return this.ВСетиField;
            }
            set {
                if ((this.ВСетиField.Equals(value) != true)) {
                    this.ВСетиField = value;
                    this.RaisePropertyChanged("ВСети");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Группа {
            get {
                return this.ГруппаField;
            }
            set {
                if ((object.ReferenceEquals(this.ГруппаField, value) != true)) {
                    this.ГруппаField = value;
                    this.RaisePropertyChanged("Группа");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string НазваниеОбъекта {
            get {
                return this.НазваниеОбъектаField;
            }
            set {
                if ((object.ReferenceEquals(this.НазваниеОбъектаField, value) != true)) {
                    this.НазваниеОбъектаField = value;
                    this.RaisePropertyChanged("НазваниеОбъекта");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> СсылкаНаАватар {
            get {
                return this.СсылкаНаАватарField;
            }
            set {
                if ((this.СсылкаНаАватарField.Equals(value) != true)) {
                    this.СсылкаНаАватарField = value;
                    this.RaisePropertyChanged("СсылкаНаАватар");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ЗадачиПользователя", Namespace="http://schemas.datacontract.org/2004/07/RosService.Services")]
    [System.SerializableAttribute()]
    public partial class ЗадачиПользователя : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal id_nodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int КоличествоField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int НовыеField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int СрочныеField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal id_node {
            get {
                return this.id_nodeField;
            }
            set {
                if ((this.id_nodeField.Equals(value) != true)) {
                    this.id_nodeField = value;
                    this.RaisePropertyChanged("id_node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Количество {
            get {
                return this.КоличествоField;
            }
            set {
                if ((this.КоличествоField.Equals(value) != true)) {
                    this.КоличествоField = value;
                    this.RaisePropertyChanged("Количество");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Новые {
            get {
                return this.НовыеField;
            }
            set {
                if ((this.НовыеField.Equals(value) != true)) {
                    this.НовыеField = value;
                    this.RaisePropertyChanged("Новые");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Срочные {
            get {
                return this.СрочныеField;
            }
            set {
                if ((this.СрочныеField.Equals(value) != true)) {
                    this.СрочныеField = value;
                    this.RaisePropertyChanged("Срочные");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IServices")]
    public interface IServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Почта_КоличествоПисем", ReplyAction="http://tempuri.org/IServices/Почта_КоличествоПисемResponse")]
        long Почта_КоличествоПисем(decimal Пользователь, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Данные_СписокТелефонов_Проиндекировать", ReplyAction="http://tempuri.org/IServices/Данные_СписокТелефонов_ПроиндекироватьResponse")]
        void Данные_СписокТелефонов_Проиндекировать(decimal id_node, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Данные_СписокТелефонов_Совпадения", ReplyAction="http://tempuri.org/IServices/Данные_СписокТелефонов_СовпаденияResponse")]
        System.Data.DataTable Данные_СписокТелефонов_Совпадения(string Телефоны, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/ПоискАдреса", ReplyAction="http://tempuri.org/IServices/ПоискАдресаResponse")]
        string[] ПоискАдреса(string Адрес, int Количество);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/ПоискБанка", ReplyAction="http://tempuri.org/IServices/ПоискБанкаResponse")]
        RosService.Services.БанкСведения[] ПоискБанка(string БИК);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/ПоискКоординатГеокодирование", ReplyAction="http://tempuri.org/IServices/ПоискКоординатГеокодированиеResponse")]
        string[] ПоискКоординатГеокодирование(string Адрес);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServices/СообщенияПользователя_Очистить")]
        void СообщенияПользователя_Очистить(decimal СсылкаНаПользователя, decimal СсылкаНаОбъект, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/СообщенияПользователя_Добавить", ReplyAction="http://tempuri.org/IServices/СообщенияПользователя_ДобавитьResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, byte[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.БанкСведения[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.БанкСведения))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СообщенияПользователя[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СообщенияПользователя))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СведенияПользователя[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СведенияПользователя))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.ЗадачиПользователя[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.ЗадачиПользователя))]
        void СообщенияПользователя_Добавить(object ОтКогоЛогинПользователя, object[] КомуЛогинПользователя, string Сообщение, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/СообщенияПользователя_Список", ReplyAction="http://tempuri.org/IServices/СообщенияПользователя_СписокResponse")]
        RosService.Services.СообщенияПользователя[] СообщенияПользователя_Список(decimal СсылкаНаПользователя, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/Пользователи_Список", ReplyAction="http://tempuri.org/IServices/Пользователи_СписокResponse")]
        RosService.Services.СведенияПользователя[] Пользователи_Список(string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/ЗадачаПользователя_Добавить", ReplyAction="http://tempuri.org/IServices/ЗадачаПользователя_ДобавитьResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, byte[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.БанкСведения[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.БанкСведения))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СообщенияПользователя[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СообщенияПользователя))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СведенияПользователя[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СведенияПользователя))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.ЗадачиПользователя[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.ЗадачиПользователя))]
        void ЗадачаПользователя_Добавить(object ОтКогоЛогинПользователя, object[] КомуЛогинПользователя, string Сообщение, bool Срочно, object Срок, System.Collections.Generic.Dictionary<string, byte[]> Файлы, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/ЗадачаПользователя_Список", ReplyAction="http://tempuri.org/IServices/ЗадачаПользователя_СписокResponse")]
        RosService.Services.ЗадачиПользователя[] ЗадачаПользователя_Список(decimal СсылкаНаПользователя, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServices/Рассылка")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, byte[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.БанкСведения[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.БанкСведения))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СообщенияПользователя[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СообщенияПользователя))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СведенияПользователя[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.СведенияПользователя))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.ЗадачиПользователя[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RosService.Services.ЗадачиПользователя))]
        void Рассылка(string Тема, string Содержание, object ПапкаАдресатами, System.Collections.Generic.Dictionary<string, byte[]> Файлы, string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/СтатистикаКонфигурации", ReplyAction="http://tempuri.org/IServices/СтатистикаКонфигурацииResponse")]
        System.Collections.Generic.Dictionary<string, object> СтатистикаКонфигурации(string user, string domain);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServices/ОптравитьВСтатистику")]
        void ОптравитьВСтатистику(string Приложение, string Источник, System.DateTime Дата, decimal Значение);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesChannel : RosService.Services.IServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<RosService.Services.IServices>, RosService.Services.IServices {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long Почта_КоличествоПисем(decimal Пользователь, string domain) {
            return base.Channel.Почта_КоличествоПисем(Пользователь, domain);
        }
        
        public void Данные_СписокТелефонов_Проиндекировать(decimal id_node, string user, string domain) {
            base.Channel.Данные_СписокТелефонов_Проиндекировать(id_node, user, domain);
        }
        
        public System.Data.DataTable Данные_СписокТелефонов_Совпадения(string Телефоны, string user, string domain) {
            return base.Channel.Данные_СписокТелефонов_Совпадения(Телефоны, user, domain);
        }
        
        public string[] ПоискАдреса(string Адрес, int Количество) {
            return base.Channel.ПоискАдреса(Адрес, Количество);
        }
        
        public RosService.Services.БанкСведения[] ПоискБанка(string БИК) {
            return base.Channel.ПоискБанка(БИК);
        }
        
        public string[] ПоискКоординатГеокодирование(string Адрес) {
            return base.Channel.ПоискКоординатГеокодирование(Адрес);
        }
        
        public void СообщенияПользователя_Очистить(decimal СсылкаНаПользователя, decimal СсылкаНаОбъект, string user, string domain) {
            base.Channel.СообщенияПользователя_Очистить(СсылкаНаПользователя, СсылкаНаОбъект, user, domain);
        }
        
        public void СообщенияПользователя_Добавить(object ОтКогоЛогинПользователя, object[] КомуЛогинПользователя, string Сообщение, string user, string domain) {
            base.Channel.СообщенияПользователя_Добавить(ОтКогоЛогинПользователя, КомуЛогинПользователя, Сообщение, user, domain);
        }
        
        public RosService.Services.СообщенияПользователя[] СообщенияПользователя_Список(decimal СсылкаНаПользователя, string user, string domain) {
            return base.Channel.СообщенияПользователя_Список(СсылкаНаПользователя, user, domain);
        }
        
        public RosService.Services.СведенияПользователя[] Пользователи_Список(string user, string domain) {
            return base.Channel.Пользователи_Список(user, domain);
        }
        
        public void ЗадачаПользователя_Добавить(object ОтКогоЛогинПользователя, object[] КомуЛогинПользователя, string Сообщение, bool Срочно, object Срок, System.Collections.Generic.Dictionary<string, byte[]> Файлы, string user, string domain) {
            base.Channel.ЗадачаПользователя_Добавить(ОтКогоЛогинПользователя, КомуЛогинПользователя, Сообщение, Срочно, Срок, Файлы, user, domain);
        }
        
        public RosService.Services.ЗадачиПользователя[] ЗадачаПользователя_Список(decimal СсылкаНаПользователя, string user, string domain) {
            return base.Channel.ЗадачаПользователя_Список(СсылкаНаПользователя, user, domain);
        }
        
        public void Рассылка(string Тема, string Содержание, object ПапкаАдресатами, System.Collections.Generic.Dictionary<string, byte[]> Файлы, string user, string domain) {
            base.Channel.Рассылка(Тема, Содержание, ПапкаАдресатами, Файлы, user, domain);
        }
        
        public System.Collections.Generic.Dictionary<string, object> СтатистикаКонфигурации(string user, string domain) {
            return base.Channel.СтатистикаКонфигурации(user, domain);
        }
        
        public void ОптравитьВСтатистику(string Приложение, string Источник, System.DateTime Дата, decimal Значение) {
            base.Channel.ОптравитьВСтатистику(Приложение, Источник, Дата, Значение);
        }
    }
}
