<?xml version="1.0" encoding="utf-8"?><Database Name="бухгалтерия" Class="ClientDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ITRF;Initial Catalog=бухгалтерия;Integrated Security=True" SettingsObjectName="RosService.Properties.Settings" SettingsPropertyName="бухгалтерияConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.assembly_tblAttribute" Member="assembly_tblAttributes">
    <Type Name="assembly_tblAttribute">
      <Column Name="id_attribute" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Namespace" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="id_parent" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="id_type" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="HashCode" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="TypeHashCode" Type="System.String" DbType="VarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(860) NOT NULL" CanBeNull="false" />
      <Column Name="Описание" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="MemberType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegisterType" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="BaseType" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="ReflectedType" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="IsReadOnly" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsAutoIncrement" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSystem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsSetDefaultValue" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>